#ifndef SHARED_NOISE_HLSL
#define SHARED_NOISE_HLSL

// https://www.shadertoy.com/view/3dVXDc
/**
    An implementation of tileable 3D Perlin-Worley noise for modeling volumetric clouds
    inspired from the chapter Real-Time Volumetric Cloudscapes by Andrew Schneider
    (Guerrilla Games). The first column is the perlin-worley noise generated by remapping
    perlin noise with the lowest frequency worley fbm. The next 3 columns are worley fbms
    with increasing frequencies, and are used to model the cloud shapes which are rendered
    in the last column. See the common tab for all the noise functions used.
*/

// Hash by David_Hoskins
#define UI0 1597334673U
#define UI1 3812015801U
#define UI2 uint2(UI0, UI1)
#define UI3 uint3(UI0, UI1, 2798796415U)
#define UIF (1.0 / float(0xffffffffU))
#include "shared_functions.hlsl"
Texture2D inCloudCurlNoise;  // Curl 噪声纹理：用于局部扰动与 FBM 模式采样

float2 hash22(float2 p)
{
    float3 a = frac(float3(p.x, p.y, p.x) * float3(123.34, 234.34, 345.65));
    a += dot(a, a + 34.45);
    return frac(float2(a.x * a.y, a.y * a.z));
}

float3 hash33(float3 p)
{
	uint3 q = uint3(int3(p)) * UI3;
	q = (q.x ^ q.y ^ q.z)*UI3;
	return -1. + 2. * float3(q) * UIF;
}

// Gradient noise by iq (modified to be tileable)
float gradientNoise(float3 x, float freq)
{
    // grid
    float3 p = floor(x);
    float3 w = frac(x);
    
    // quintic interpolant
    float3 u = w * w * w * (w * (w * 6. - 15.) + 10.);
    
    // gradients
    float3 ga = hash33(mod(p + float3(0., 0., 0.), freq));
    float3 gb = hash33(mod(p + float3(1., 0., 0.), freq));
    float3 gc = hash33(mod(p + float3(0., 1., 0.), freq));
    float3 gd = hash33(mod(p + float3(1., 1., 0.), freq));
    float3 ge = hash33(mod(p + float3(0., 0., 1.), freq));
    float3 gf = hash33(mod(p + float3(1., 0., 1.), freq));
    float3 gg = hash33(mod(p + float3(0., 1., 1.), freq));
    float3 gh = hash33(mod(p + float3(1., 1., 1.), freq));
    
    // projections
    float va = dot(ga, w - float3(0., 0., 0.));
    float vb = dot(gb, w - float3(1., 0., 0.));
    float vc = dot(gc, w - float3(0., 1., 0.));
    float vd = dot(gd, w - float3(1., 1., 0.));
    float ve = dot(ge, w - float3(0., 0., 1.));
    float vf = dot(gf, w - float3(1., 0., 1.));
    float vg = dot(gg, w - float3(0., 1., 1.));
    float vh = dot(gh, w - float3(1., 1., 1.));
	
    // interpolation
    return va + 
           u.x * (vb - va) + 
           u.y * (vc - va) + 
           u.z * (ve - va) + 
           u.x * u.y * (va - vb - vc + vd) + 
           u.y * u.z * (va - vc - ve + vg) + 
           u.z * u.x * (va - vb - ve + vf) + 
           u.x * u.y * u.z * (-va + vb + vc - vd + ve - vf - vg + vh);
}

// Tileable 3D worley noise
float worleyNoise(float3 uv, float freq)
{    
    float3 id = floor(uv);
    float3 p = frac(uv);
    
    float minDist = 10000.;
    for (float x = -1.; x <= 1.; ++x)
    {
        for(float y = -1.; y <= 1.; ++y)
        {
            for(float z = -1.; z <= 1.; ++z)
            {
                float3 offset = float3(x, y, z);
            	float3 h = hash33(mod(id + offset, float3(freq,freq,freq))) * .5 + .5;
    			h += offset;
            	float3 d = p - h;
           		minDist = min(minDist, dot(d, d));
            }
        }
    }
    
    // inverted worley noise
    return 1. - minDist;
}

// Fbm for Perlin noise based on iq's blog
float perlinfbm(float3 p, float freq, int octaves)
{
    float G = exp2(-.85);
    float amp = 1.;
    float noise = 0.;
    for (int i = 0; i < octaves; ++i)
    {
        noise += amp * gradientNoise(p * freq, freq);
        freq *= 2.;
        amp *= G;
    }
    
    return noise;
}

// Tileable Worley fbm inspired by Andrew Schneider's Real-Time Volumetric Cloudscapes
// chapter in GPU Pro 7.
float worleyFbm(float3 p, float freq)
{
    return worleyNoise(p*freq, freq) * .625 +
           worleyNoise(p*freq*2., freq*2.) * .25 +
           worleyNoise(p*freq*4., freq*4.) * .125;
}

//=======================================================

float4 Voronoi2D (float2 p,float numClumps,float numClumpTypes)
{
    float minDist = 100000.0;
    float id = 0.0;
    float2 clumpCentre = float2(0.0, 0.0);

    int clumpLimit = min(100,(int)numClumps);

    for (int j=1;j<clumpLimit;j++)
    {
        float2 gridCell = float2(float(j),float(j));
        float2 point_ =  hash22(gridCell);
        float dist = distance(point_,p);
        if (dist<minDist)
        {
            minDist=dist;
            id=mod( float(j),numClumpTypes);
            clumpCentre=point_;
        }
    }

    float3 col =float3(id,clumpCentre.x,clumpCentre.y);
    return float4(col,1.0);
}



#endif